linkinpark = [
["1stp Klosr", "../lyrics/linkinpark/1stpklosr.html", "", ""],
["26 Lettaz In Da Alphabet", "../lyrics/linkinpark/26lettazindaalphabet.html", "", ""],
["A Light That Never Comes", "../lyrics/linkinpark/alightthatnevercomes.html", "", ""],
["A Light That Never Comes (Rick Rubin Remix)", "../lyrics/linkinpark/alightthatnevercomesrickrubinremix.html", "", ""],
["A Line In The Sand", "../lyrics/linkinpark/alineinthesand.html", "", ""],
["A Place For My Head", "../lyrics/linkinpark/aplaceformyhead.html", "", ""],
["Across The Line", "../lyrics/linkinpark/acrosstheline.html", "", ""],
["Across The Line (Unreleased 2007 Demo)", "../lyrics/linkinpark/acrossthelineunreleased2007demo.html", "", ""],
["All For Nothing", "../lyrics/linkinpark/allfornothing.html", "", ""],
["And One", "../lyrics/linkinpark/andone.html", "", ""],
["Animals (2011 Demo)", "../lyrics/linkinpark/animals2011demo.html", "", ""],
["Announcement Service Public", "../lyrics/linkinpark/announcementservicepublic.html", "", ""],
["Apaches (Until It Breaks Demo, No. 1)", "../lyrics/linkinpark/apachesuntilitbreaksdemono1.html", "", ""],
["Asbestos (Minutes To Midnight Demo)", "../lyrics/linkinpark/asbestosminutestomidnightdemo.html", "", ""],
["Basil (2008 Demo)", "../lyrics/linkinpark/basil2008demo.html", "", ""],
["Big Pimpin' / Papercut", "../lyrics/linkinpark/bigpimpinpapercut.html", "", ""],
["Blackbirds", "../lyrics/linkinpark/blackbirds.html", "", ""],
["Blackout", "../lyrics/linkinpark/blackout.html", "", ""],
["Bleed It Out", "../lyrics/linkinpark/bleeditout.html", "", ""],
["Bleed It Out (2007 Demo)", "../lyrics/linkinpark/bleeditout2007demo.html", "", ""],
["Blue (1998 Unreleased Hybrid Theory Demo)", "../lyrics/linkinpark/blue1998unreleasedhybridtheorydemo.html", "", ""],
["Breaking The Habit", "../lyrics/linkinpark/breakingthehabit.html", "", ""],
["Breaking The Habit (Original Mike 2002 Demo)", "../lyrics/linkinpark/breakingthehabitoriginalmike2002demo.html", "", ""],
["Bubbles", "../lyrics/linkinpark/bubbles.html", "", ""],
["Burn It Down", "../lyrics/linkinpark/burnitdown.html", "", ""],
["Burn It Down (Paul Van Dyk Remix)", "../lyrics/linkinpark/burnitdownpaulvandykremix.html", "", ""],
["Burn It Down (Tom Swoon Remix)", "../lyrics/linkinpark/burnitdowntomswoonremix.html", "", ""],
["Burning In The Skies", "../lyrics/linkinpark/burningintheskies.html", "", ""],
["By Myself", "../lyrics/linkinpark/bymyself.html", "", ""],
["By_Myslf", "../lyrics/linkinpark/bymyslf.html", "", ""],
["Carousel", "../lyrics/linkinpark/carousel.html", "", ""],
["Castle Of Glass", "../lyrics/linkinpark/castleofglass.html", "", ""],
["Castle Of Glass (M. Shinoda Remix)", "../lyrics/linkinpark/castleofglassmshinodaremix.html", "", ""],
["Chali", "../lyrics/linkinpark/chali.html", "", ""],
["Chance Of Rain (2006 Demo)", "../lyrics/linkinpark/chanceofrain2006demo.html", "", ""],
["Change (By Beta State, LPU Sessions 2013)", "../lyrics/linkinpark/changebybetastatelpusessions2013.html", "", ""],
["Crawling", "../lyrics/linkinpark/crawling.html", "", ""],
["Cure For The Itch", "../lyrics/linkinpark/curefortheitch.html", "", ""],
["Da Bloos", "../lyrics/linkinpark/dabloos.html", "", ""],
["Dave Sbeat", "../lyrics/linkinpark/davesbeat.html", "", ""],
["Debris (Minutes To Midnight Demo)", "../lyrics/linkinpark/debrisminutestomidnightdemo.html", "", ""],
["Dedicated", "../lyrics/linkinpark/dedicated.html", "", ""],
["Devil's Drop", "../lyrics/linkinpark/devilsdrop.html", "", ""],
["Dirt Off Your Shoulder / Lying From You", "../lyrics/linkinpark/dirtoffyourshoulderlyingfromyou.html", "", ""],
["Don't Stay", "../lyrics/linkinpark/dontstay.html", "", ""],
["Drum Song (Little Things Give You Away 2006 Demo)", "../lyrics/linkinpark/drumsonglittlethingsgiveyouaway2006demo.html", "", ""],
["Easier To Run", "../lyrics/linkinpark/easiertorun.html", "", ""],
["Enth E Nd", "../lyrics/linkinpark/enthend.html", "", ""],
["Esaul (A Place For My Head Demo)", "../lyrics/linkinpark/esaulaplaceformyheaddemo.html", "", ""],
["Faint", "../lyrics/linkinpark/faint.html", "", ""],
["Faint (2002 Demo)", "../lyrics/linkinpark/faint2002demo.html", "", ""],
["Fallout", "../lyrics/linkinpark/fallout.html", "", ""],
["Fear (Leave Out All The Rest 2002 Demo)", "../lyrics/linkinpark/fearleaveoutalltherest2002demo.html", "", ""],
["Figure.09", "../lyrics/linkinpark/figure09.html", "", ""],
["Figure.09 (2002 Demo)", "../lyrics/linkinpark/figure092002demo.html", "", ""],
["Final Masquerade", "../lyrics/linkinpark/finalmasquerade.html", "", ""],
["Foot Patrol (Until It Breaks Demo, No. 2)", "../lyrics/linkinpark/footpatroluntilitbreaksdemono2.html", "", ""],
["Forget", "../lyrics/linkinpark/forget.html", "", ""],
["Forgotten", "../lyrics/linkinpark/forgotten.html", "", ""],
["Forgotten (Demo)", "../lyrics/linkinpark/forgottendemo.html", "", ""],
["Frgt/10", "../lyrics/linkinpark/frgt10.html", "", ""],
["From The Inside", "../lyrics/linkinpark/fromtheinside.html", "", ""],
["Fuse", "../lyrics/linkinpark/fuse.html", "", ""],
["Given Up", "../lyrics/linkinpark/givenup.html", "", ""],
["Guilty All The Same", "../lyrics/linkinpark/guiltyallthesame.html", "", ""],
["H! Vltg3", "../lyrics/linkinpark/hvltg3.html", "", ""],
["Hands Held High", "../lyrics/linkinpark/handsheldhigh.html", "", ""],
["High Voltage", "../lyrics/linkinpark/highvoltage.html", "", ""],
["High Voltage (Remix)", "../lyrics/linkinpark/highvoltageremix.html", "", ""],
["Hit The Floor", "../lyrics/linkinpark/hitthefloor.html", "", ""],
["Hunger Strike", "../lyrics/linkinpark/hungerstrike.html", "", ""],
["I Have Not Begun", "../lyrics/linkinpark/ihavenotbegun.html", "", ""],
["I Have Not Begun (2009 Demo)", "../lyrics/linkinpark/ihavenotbegun2009demo.html", "", ""],
["I'll Be Gone", "../lyrics/linkinpark/illbegone.html", "", ""],
["I'll Be Gone (Schoolboy Remix)", "../lyrics/linkinpark/illbegoneschoolboyremix.html", "", ""],
["I'll Be Gone (Vice Remix)", "../lyrics/linkinpark/illbegoneviceremix.html", "", ""],
["In Between", "../lyrics/linkinpark/inbetween.html", "", ""],
["In My Remains", "../lyrics/linkinpark/inmyremains.html", "", ""],
["In Pieces", "../lyrics/linkinpark/inpieces.html", "", ""],
["In The End", "../lyrics/linkinpark/intheend.html", "", ""],
["In The End (Demo)", "../lyrics/linkinpark/intheenddemo.html", "", ""],
["Iridescent", "../lyrics/linkinpark/iridescent.html", "", ""],
["It Goes Through", "../lyrics/linkinpark/itgoesthrough.html", "", ""],
["It's Going Down", "../lyrics/linkinpark/itsgoingdown.html", "", ""],
["Izzo / In The End", "../lyrics/linkinpark/izzointheend.html", "", ""],
["Jigga What / Faint", "../lyrics/linkinpark/jiggawhatfaint.html", "", ""],
["Jornada Del Muerto", "../lyrics/linkinpark/jornadadelmuerto.html", "", ""],
["Keys To The Kingdom", "../lyrics/linkinpark/keystothekingdom.html", "", ""],
["Krwlng", "../lyrics/linkinpark/krwlng.html", "", ""],
["Kyur4 Th Ich", "../lyrics/linkinpark/kyur4thich.html", "", ""],
["Last Line", "../lyrics/linkinpark/lastline.html", "", ""],
["Leave Out All The Rest", "../lyrics/linkinpark/leaveoutalltherest.html", "", ""],
["Lies Greed Misery", "../lyrics/linkinpark/liesgreedmisery.html", "", ""],
["Lies Greed Misery (Dirtyphonics Remix)", "../lyrics/linkinpark/liesgreedmiserydirtyphonicsremix.html", "", ""],
["Lost In The Echo", "../lyrics/linkinpark/lostintheecho.html", "", ""],
["Lost In The Echo (Killsonik Remix)", "../lyrics/linkinpark/lostintheechokillsonikremix.html", "", ""],
["Lying From You", "../lyrics/linkinpark/lyingfromyou.html", "", ""],
["Mark The Graves", "../lyrics/linkinpark/markthegraves.html", "", ""],
["Morning After", "../lyrics/linkinpark/morningafter.html", "", ""],
["My December", "../lyrics/linkinpark/mydecember.html", "", ""],
["My[Dsmbr", "../lyrics/linkinpark/mydsmbr.html", "", ""],
["New Divide", "../lyrics/linkinpark/newdivide.html", "", ""],
["No Laundry", "../lyrics/linkinpark/nolaundry.html", "", ""],
["No More Sorrow", "../lyrics/linkinpark/nomoresorrow.html", "", ""],
["No Roads Left", "../lyrics/linkinpark/noroadsleft.html", "", ""],
["Nobody’s Listening", "../lyrics/linkinpark/nobodyslistening.html", "", ""],
["Not Alone", "../lyrics/linkinpark/notalone.html", "", ""],
["Numb", "../lyrics/linkinpark/numb.html", "", ""],
["Numb / Encore", "../lyrics/linkinpark/numbencore.html", "", ""],
["One Perfect Something", "../lyrics/linkinpark/oneperfectsomething.html", "", ""],
["One Step Closer", "../lyrics/linkinpark/onestepcloser.html", "", ""],
["Over The Top", "../lyrics/linkinpark/overthetop.html", "", ""],
["P5hng Me A*wy", "../lyrics/linkinpark/p5hngmeawy.html", "", ""],
["Papercut", "../lyrics/linkinpark/papercut.html", "", ""],
["Part Of Me", "../lyrics/linkinpark/partofme.html", "", ""],
["PB N' Jellyfish", "../lyrics/linkinpark/pbnjellyfish.html", "", ""],
["Plc.4 Mie Haed", "../lyrics/linkinpark/plc4miehaed.html", "", ""],
["Points Of Authority", "../lyrics/linkinpark/pointsofauthority.html", "", ""],
["Points Of Authority (Demo)", "../lyrics/linkinpark/pointsofauthoritydemo.html", "", ""],
["Points Of Authority / 99 Problems / One Step Closer", "../lyrics/linkinpark/pointsofauthority99problemsonestepcloser.html", "", ""],
["Powerless", "../lyrics/linkinpark/powerless.html", "", ""],
["Powerless (Enferno Remix)", "../lyrics/linkinpark/powerlessenfernoremix.html", "", ""],
["PPr:Kut", "../lyrics/linkinpark/pprkut.html", "", ""],
["Pretend To Be", "../lyrics/linkinpark/pretendtobe.html", "", ""],
["Pretend To Be (2008 Demo)", "../lyrics/linkinpark/pretendtobe2008demo.html", "", ""],
["Primo (I'll Be Gone, Longform 2010 Demo)", "../lyrics/linkinpark/primoillbegonelongform2010demo.html", "", ""],
["Pts.Of.Athrty", "../lyrics/linkinpark/ptsofathrty.html", "", ""],
["Pushing Me Away", "../lyrics/linkinpark/pushingmeaway.html", "", ""],
["Qwerty", "../lyrics/linkinpark/qwerty.html", "", ""],
["Reading My Eyes", "../lyrics/linkinpark/readingmyeyes.html", "", ""],
["Rebellion", "../lyrics/linkinpark/rebellion.html", "", ""],
["Rhinestone", "../lyrics/linkinpark/rhinestone.html", "", ""],
["Riff Raff", "../lyrics/linkinpark/riffraff.html", "", ""],
["Rnw@y", "../lyrics/linkinpark/rnwy.html", "", ""],
["Roads Untraveled", "../lyrics/linkinpark/roadsuntraveled.html", "", ""],
["Roads Untraveled (Rad Omen Remix)", "../lyrics/linkinpark/roadsuntraveledradomenremix.html", "", ""],
["Robot Boy", "../lyrics/linkinpark/robotboy.html", "", ""],
["Robot Boy (Test Mix, Option Vocal Take)", "../lyrics/linkinpark/robotboytestmixoptionvocaltake.html", "", ""],
["Rolling In The Deep", "../lyrics/linkinpark/rollinginthedeep.html", "", ""],
["Runaway", "../lyrics/linkinpark/runaway.html", "", ""],
["Shadow Of The Day", "../lyrics/linkinpark/shadowoftheday.html", "", ""],
["She Couldn't", "../lyrics/linkinpark/shecouldnt.html", "", ""],
["Skin To Bone", "../lyrics/linkinpark/skintobone.html", "", ""],
["Skin To Bone (Nick Catchdubs Remix)", "../lyrics/linkinpark/skintobonenickcatchdubsremix.html", "", ""],
["Slip (1998 Unreleased Hybrid Theory Demo)", "../lyrics/linkinpark/slip1998unreleasedhybridtheorydemo.html", "", ""],
["So Far Away (Unreleased 1998)", "../lyrics/linkinpark/sofarawayunreleased1998.html", "", ""],
["Sold My Soul To Yo Mama", "../lyrics/linkinpark/soldmysoultoyomama.html", "", ""],
["Somewhere I Belong", "../lyrics/linkinpark/somewhereibelong.html", "", ""],
["Standing In The Middle", "../lyrics/linkinpark/standinginthemiddle.html", "", ""],
["Starting To Fly", "../lyrics/linkinpark/startingtofly.html", "", ""],
["Stef", "../lyrics/linkinpark/stef.html", "", ""],
["Step Up", "../lyrics/linkinpark/stepup.html", "", ""],
["Stick N' Move", "../lyrics/linkinpark/sticknmove.html", "", ""],
["Super Xero (By Myself)", "../lyrics/linkinpark/superxerobymyself.html", "", ""],
["System", "../lyrics/linkinpark/system.html", "", ""],
["The Catalyst", "../lyrics/linkinpark/thecatalyst.html", "", ""],
["The Last Line", "../lyrics/linkinpark/thelastline.html", "", ""],
["The Little Things Give You Away", "../lyrics/linkinpark/thelittlethingsgiveyouaway.html", "", ""],
["The Messenger", "../lyrics/linkinpark/themessenger.html", "", ""],
["The Radiance", "../lyrics/linkinpark/theradiance.html", "", ""],
["The Requiem", "../lyrics/linkinpark/therequiem.html", "", ""],
["Three Band Terror (Until It Breaks, No. 3)", "../lyrics/linkinpark/threebandterroruntilitbreaksno3.html", "", ""],
["Until It Breaks", "../lyrics/linkinpark/untilitbreaks.html", "", ""],
["Until It Breaks (Datsik Remix)", "../lyrics/linkinpark/untilitbreaksdatsikremix.html", "", ""],
["Until It Breaks (Money Mark Headphone Remix)", "../lyrics/linkinpark/untilitbreaksmoneymarkheadphoneremix.html", "", ""],
["Until It's Gone", "../lyrics/linkinpark/untilitsgone.html", "", ""],
["Valentine's Day", "../lyrics/linkinpark/valentinesday.html", "", ""],
["Vertical Limit (Points Of Authority Demo)", "../lyrics/linkinpark/verticallimitpointsofauthoritydemo.html", "", ""],
["Victimized", "../lyrics/linkinpark/victimized.html", "", ""],
["Victimized (M. Shinoda Remix)", "../lyrics/linkinpark/victimizedmshinodaremix.html", "", ""],
["Waiting For The End", "../lyrics/linkinpark/waitingfortheend.html", "", ""],
["Walking Dead", "../lyrics/linkinpark/walkingdead.html", "", ""],
["War", "../lyrics/linkinpark/war.html", "", ""],
["Wastelands", "../lyrics/linkinpark/wastelands.html", "", ""],
["What I've Done", "../lyrics/linkinpark/whativedone.html", "", ""],
["What I've Done (Mike Shinoda Remix)", "../lyrics/linkinpark/whativedonemikeshinodaremix.html", "", ""],
["What We Don't Know", "../lyrics/linkinpark/whatwedontknow.html", "", ""],
["What We Don't Know (2007 Demo)", "../lyrics/linkinpark/whatwedontknow2007demo.html", "", ""],
["When They Come For Me", "../lyrics/linkinpark/whentheycomeforme.html", "", ""],
["White Noise", "../lyrics/linkinpark/whitenoise.html", "", ""],
["Wisdom, Justice And Love", "../lyrics/linkinpark/wisdomjusticeandlove.html", "", ""],
["With You", "../lyrics/linkinpark/withyou.html", "", ""],
["Wretches And Kings", "../lyrics/linkinpark/wretchesandkings.html", "", ""],
["Wth&gt;You", "../lyrics/linkinpark/wthyou.html", "", ""],
["X-Ecutioner Style", "../lyrics/linkinpark/xecutionerstyle.html", "", ""],
["You Ain't Gotsta Gotsta", "../lyrics/linkinpark/youaintgotstagotsta.html", "", ""]]

taylorswift = [
["22", "../lyrics/taylorswift/22.html", "", ""],
["A Perfectly Good Heart", "../lyrics/taylorswift/aperfectlygoodheart.html", "", ""],
["A Place In This World", "../lyrics/taylorswift/aplaceinthisworld.html", "", ""],
["Ain't Nothing 'Bout You", "../lyrics/taylorswift/aintnothingboutyou.html", "", ""],
["All Because Of Ellen", "../lyrics/taylorswift/allbecauseofellen.html", "", ""],
["All Night Diner", "../lyrics/taylorswift/allnightdiner.html", "", ""],
["All Too Well", "../lyrics/taylorswift/alltoowell.html", "", ""],
["All You Had To Do Was Stay", "../lyrics/taylorswift/allyouhadtodowasstay.html", "", ""],
["Am I Ready For Love", "../lyrics/taylorswift/amireadyforlove.html", "", ""],
["American Boy", "../lyrics/taylorswift/americanboy.html", "", ""],
["American Girl", "../lyrics/taylorswift/americangirl.html", "", ""],
["Angelina", "../lyrics/taylorswift/angelina.html", "", ""],
["Baby, Don't You Break My Heart Slow", "../lyrics/taylorswift/babydontyoubreakmyheartslow.html", "", ""],
["Back To December", "../lyrics/taylorswift/backtodecember.html", "", ""],
["Back To December / Apologize / You're Not Sorry", "../lyrics/taylorswift/backtodecemberapologizeyourenotsorry.html", "", ""],
["Bad Blood", "../lyrics/taylorswift/badblood.html", "", ""],
["Bad Blood (Remix)", "../lyrics/taylorswift/badbloodremix.html", "", ""],
["Beautiful Eyes", "../lyrics/taylorswift/beautifuleyes.html", "", ""],
["Begin Again", "../lyrics/taylorswift/beginagain.html", "", ""],
["Being With My Baby", "../lyrics/taylorswift/beingwithmybaby.html", "", ""],
["Bette Davis Eyes", "../lyrics/taylorswift/bettedaviseyes.html", "", ""],
["Better Off", "../lyrics/taylorswift/betteroff.html", "", ""],
["Better Than Revenge", "../lyrics/taylorswift/betterthanrevenge.html", "", ""],
["Blank Space", "../lyrics/taylorswift/blankspace.html", "", ""],
["Breathe", "../lyrics/taylorswift/breathe.html", "", ""],
["Breathless", "../lyrics/taylorswift/breathless.html", "", ""],
["Brought Up That Way", "../lyrics/taylorswift/broughtupthatway.html", "", ""],
["By The Way", "../lyrics/taylorswift/bytheway.html", "", ""],
["Can I Go With You", "../lyrics/taylorswift/canigowithyou.html", "", ""],
["Change", "../lyrics/taylorswift/change.html", "", ""],
["Christmas Must Be Something More", "../lyrics/taylorswift/christmasmustbesomethingmore.html", "", ""],
["Christmases When You Were Mine", "../lyrics/taylorswift/christmaseswhenyouweremine.html", "", ""],
["Clean", "../lyrics/taylorswift/clean.html", "", ""],
["Closest To A Cowboy", "../lyrics/taylorswift/closesttoacowboy.html", "", ""],
["Cold As You", "../lyrics/taylorswift/coldasyou.html", "", ""],
["Come Back... Be Here", "../lyrics/taylorswift/comebackbehere.html", "", ""],
["Come In With The Rain", "../lyrics/taylorswift/comeinwiththerain.html", "", ""],
["Crazier", "../lyrics/taylorswift/crazier.html", "", ""],
["Cross My Heart", "../lyrics/taylorswift/crossmyheart.html", "", ""],
["Dark Blue Tennessee", "../lyrics/taylorswift/darkbluetennessee.html", "", ""],
["Dear John", "../lyrics/taylorswift/dearjohn.html", "", ""],
["Didn't They", "../lyrics/taylorswift/didntthey.html", "", ""],
["Don't Hate Me For Loving You", "../lyrics/taylorswift/donthatemeforlovingyou.html", "", ""],
["Down Came The Rain", "../lyrics/taylorswift/downcametherain.html", "", ""],
["Drops Of Jupiter", "../lyrics/taylorswift/dropsofjupiter.html", "", ""],
["Enchanted", "../lyrics/taylorswift/enchanted.html", "", ""],
["Everything Has Changed", "../lyrics/taylorswift/everythinghaschanged.html", "", ""],
["Eyes Open", "../lyrics/taylorswift/eyesopen.html", "", ""],
["Fall Back On You", "../lyrics/taylorswift/fallbackonyou.html", "", ""],
["Fearless", "../lyrics/taylorswift/fearless.html", "", ""],
["Fifteen", "../lyrics/taylorswift/fifteen.html", "", ""],
["Firefly", "../lyrics/taylorswift/firefly.html", "", ""],
["Forever &amp; Always", "../lyrics/taylorswift/foreveralways.html", "", ""],
["Forever &amp; Always (Piano Version)", "../lyrics/taylorswift/foreveralwayspianoversion.html", "", ""],
["Girl At Home", "../lyrics/taylorswift/girlathome.html", "", ""],
["Gracie", "../lyrics/taylorswift/gracie.html", "", ""],
["Haunted", "../lyrics/taylorswift/haunted.html", "", ""],
["Hey Stephen", "../lyrics/taylorswift/heystephen.html", "", ""],
["Holy Ground", "../lyrics/taylorswift/holyground.html", "", ""],
["Hopelessly Devoted To You", "../lyrics/taylorswift/hopelesslydevotedtoyou.html", "", ""],
["How You Get The Girl", "../lyrics/taylorswift/howyougetthegirl.html", "", ""],
["I Almost Do", "../lyrics/taylorswift/ialmostdo.html", "", ""],
["I Heart ?", "../lyrics/taylorswift/iheart.html", "", ""],
["I Knew You Were Trouble", "../lyrics/taylorswift/iknewyouweretrouble.html", "", ""],
["I Knew You Were Trouble (Remix)", "../lyrics/taylorswift/iknewyouweretroubleremix.html", "", ""],
["I Know Places", "../lyrics/taylorswift/iknowplaces.html", "", ""],
["I Know What I Want", "../lyrics/taylorswift/iknowwhatiwant.html", "", ""],
["I Used To Fly", "../lyrics/taylorswift/iusedtofly.html", "", ""],
["I Want You Back", "../lyrics/taylorswift/iwantyouback.html", "", ""],
["I Wish You Would", "../lyrics/taylorswift/iwishyouwould.html", "", ""],
["I Wished On A Plane", "../lyrics/taylorswift/iwishedonaplane.html", "", ""],
["I'd Lie", "../lyrics/taylorswift/idlie.html", "", ""],
["I'm Only Me When I'm With You", "../lyrics/taylorswift/imonlymewhenimwithyou.html", "", ""],
["If This Was A Movie", "../lyrics/taylorswift/ifthiswasamovie.html", "", ""],
["Innocent", "../lyrics/taylorswift/innocent.html", "", ""],
["Invisible", "../lyrics/taylorswift/invisible.html", "", ""],
["Jump Then Fall", "../lyrics/taylorswift/jumpthenfall.html", "", ""],
["Just South Of Knowing Why", "../lyrics/taylorswift/justsouthofknowingwhy.html", "", ""],
["Last Christmas", "../lyrics/taylorswift/lastchristmas.html", "", ""],
["Last Kiss", "../lyrics/taylorswift/lastkiss.html", "", ""],
["Long Live", "../lyrics/taylorswift/longlive.html", "", ""],
["Long Time Coming", "../lyrics/taylorswift/longtimecoming.html", "", ""],
["Love Story", "../lyrics/taylorswift/lovestory.html", "", ""],
["Love To Lose", "../lyrics/taylorswift/lovetolose.html", "", ""],
["Lucky You", "../lyrics/taylorswift/luckyyou.html", "", ""],
["Made Up You", "../lyrics/taylorswift/madeupyou.html", "", ""],
["Making Up For Lost Love", "../lyrics/taylorswift/makingupforlostlove.html", "", ""],
["Mandolin", "../lyrics/taylorswift/mandolin.html", "", ""],
["Mary's Song (Oh My My My)", "../lyrics/taylorswift/maryssongohmymymy.html", "", ""],
["Matches", "../lyrics/taylorswift/matches.html", "", ""],
["Me And Britney", "../lyrics/taylorswift/meandbritney.html", "", ""],
["Mean", "../lyrics/taylorswift/mean.html", "", ""],
["Mine", "../lyrics/taylorswift/mine.html", "", ""],
["Monologue Song (La La La)", "../lyrics/taylorswift/monologuesonglalala.html", "", ""],
["My Cure", "../lyrics/taylorswift/mycure.html", "", ""],
["My Turn To Be Me", "../lyrics/taylorswift/myturntobeme.html", "", ""],
["Nashville", "../lyrics/taylorswift/nashville.html", "", ""],
["Need You Now", "../lyrics/taylorswift/needyounow.html", "", ""],
["Never Fade", "../lyrics/taylorswift/neverfade.html", "", ""],
["Never Grow Up", "../lyrics/taylorswift/nevergrowup.html", "", ""],
["Nevermind", "../lyrics/taylorswift/nevermind.html", "", ""],
["New Romantics", "../lyrics/taylorswift/newromantics.html", "", ""],
["One Thing", "../lyrics/taylorswift/onething.html", "", ""],
["One Way Ticket", "../lyrics/taylorswift/onewayticket.html", "", ""],
["Our Last Night", "../lyrics/taylorswift/ourlastnight.html", "", ""],
["Our Song", "../lyrics/taylorswift/oursong.html", "", ""],
["Ours", "../lyrics/taylorswift/ours.html", "", ""],
["Out Of The Woods", "../lyrics/taylorswift/outofthewoods.html", "", ""],
["Permanent Marker", "../lyrics/taylorswift/permanentmarker.html", "", ""],
["Picture To Burn", "../lyrics/taylorswift/picturetoburn.html", "", ""],
["Red", "../lyrics/taylorswift/red.html", "", ""],
["Revenge", "../lyrics/taylorswift/revenge.html", "", ""],
["Riptide", "../lyrics/taylorswift/riptide.html", "", ""],
["Ronan", "../lyrics/taylorswift/ronan.html", "", ""],
["Run", "../lyrics/taylorswift/run.html", "", ""],
["Sad Beautiful Tragic", "../lyrics/taylorswift/sadbeautifultragic.html", "", ""],
["Safe &amp; Sound", "../lyrics/taylorswift/safesound.html", "", ""],
["Same Girl", "../lyrics/taylorswift/samegirl.html", "", ""],
["Santa Baby", "../lyrics/taylorswift/santababy.html", "", ""],
["Shake It Off", "../lyrics/taylorswift/shakeitoff.html", "", ""],
["Should've Said No", "../lyrics/taylorswift/shouldvesaidno.html", "", ""],
["Silent Night", "../lyrics/taylorswift/silentnight.html", "", ""],
["Smokey Black Nights", "../lyrics/taylorswift/smokeyblacknights.html", "", ""],
["Sparks Fly", "../lyrics/taylorswift/sparksfly.html", "", ""],
["Speak Now", "../lyrics/taylorswift/speaknow.html", "", ""],
["Spinning Around", "../lyrics/taylorswift/spinningaround.html", "", ""],
["Starlight", "../lyrics/taylorswift/starlight.html", "", ""],
["State Of Grace", "../lyrics/taylorswift/stateofgrace.html", "", ""],
["Stay Beautiful", "../lyrics/taylorswift/staybeautiful.html", "", ""],
["Stay Stay Stay", "../lyrics/taylorswift/staystaystay.html", "", ""],
["Stupid Boy", "../lyrics/taylorswift/stupidboy.html", "", ""],
["Style", "../lyrics/taylorswift/style.html", "", ""],
["Superman", "../lyrics/taylorswift/superman.html", "", ""],
["Superstar", "../lyrics/taylorswift/superstar.html", "", ""],
["Sweet Escape", "../lyrics/taylorswift/sweetescape.html", "", ""],
["Sweet Tea And God's Graces", "../lyrics/taylorswift/sweetteaandgodsgraces.html", "", ""],
["Sweeter Than Fiction", "../lyrics/taylorswift/sweeterthanfiction.html", "", ""],
["Teardrops On My Guitar", "../lyrics/taylorswift/teardropsonmyguitar.html", "", ""],
["Tell Me", "../lyrics/taylorswift/tellme.html", "", ""],
["Tell Me Why", "../lyrics/taylorswift/tellmewhy.html", "", ""],
["Ten Dollars And A Six Pack", "../lyrics/taylorswift/tendollarsandasixpack.html", "", ""],
["That's When", "../lyrics/taylorswift/thatswhen.html", "", ""],
["The Best Day", "../lyrics/taylorswift/thebestday.html", "", ""],
["The Diary Of Me", "../lyrics/taylorswift/thediaryofme.html", "", ""],
["The Last Time", "../lyrics/taylorswift/thelasttime.html", "", ""],
["The Lucky One", "../lyrics/taylorswift/theluckyone.html", "", ""],
["The Moment I Knew", "../lyrics/taylorswift/themomentiknew.html", "", ""],
["The Other Side Of The Door", "../lyrics/taylorswift/theothersideofthedoor.html", "", ""],
["The Outside", "../lyrics/taylorswift/theoutside.html", "", ""],
["The Story Of Us", "../lyrics/taylorswift/thestoryofus.html", "", ""],
["The Way I Loved You", "../lyrics/taylorswift/thewayilovedyou.html", "", ""],
["There's Your Trouble", "../lyrics/taylorswift/theresyourtrouble.html", "", ""],
["Thirteen Blocks (Can't Call It Love)", "../lyrics/taylorswift/thirteenblockscantcallitlove.html", "", ""],
["This Here Guitar", "../lyrics/taylorswift/thishereguitar.html", "", ""],
["This Is Really Happening", "../lyrics/taylorswift/thisisreallyhappening.html", "", ""],
["This Love", "../lyrics/taylorswift/thislove.html", "", ""],
["Thug Story", "../lyrics/taylorswift/thugstory.html", "", ""],
["Tied Together With A Smile", "../lyrics/taylorswift/tiedtogetherwithasmile.html", "", ""],
["Til Brad Pitt Comes Along", "../lyrics/taylorswift/tilbradpittcomesalong.html", "", ""],
["Tim McGraw", "../lyrics/taylorswift/timmcgraw.html", "", ""],
["Today Was A Fairytale", "../lyrics/taylorswift/todaywasafairytale.html", "", ""],
["Treacherous", "../lyrics/taylorswift/treacherous.html", "", ""],
["Under My Head", "../lyrics/taylorswift/undermyhead.html", "", ""],
["Untouchable", "../lyrics/taylorswift/untouchable.html", "", ""],
["Viva La Vida", "../lyrics/taylorswift/vivalavida.html", "", ""],
["Wait For Me", "../lyrics/taylorswift/waitforme.html", "", ""],
["We Are Never Ever Getting Back Together", "../lyrics/taylorswift/weareneverevergettingbacktogether.html", "", ""],
["We Were Happy", "../lyrics/taylorswift/wewerehappy.html", "", ""],
["Welcome Distraction", "../lyrics/taylorswift/welcomedistraction.html", "", ""],
["Welcome To New York", "../lyrics/taylorswift/welcometonewyork.html", "", ""],
["What Do You Say", "../lyrics/taylorswift/whatdoyousay.html", "", ""],
["What To Wear", "../lyrics/taylorswift/whattowear.html", "", ""],
["White Christmas", "../lyrics/taylorswift/whitechristmas.html", "", ""],
["White Horse", "../lyrics/taylorswift/whitehorse.html", "", ""],
["Who I've Always Been", "../lyrics/taylorswift/whoivealwaysbeen.html", "", ""],
["Wildest Dreams", "../lyrics/taylorswift/wildestdreams.html", "", ""],
["Wonderland", "../lyrics/taylorswift/wonderland.html", "", ""],
["Writing Songs About You", "../lyrics/taylorswift/writingsongsaboutyou.html", "", ""],
["You Are In Love", "../lyrics/taylorswift/youareinlove.html", "", ""],
["You Belong With Me", "../lyrics/taylorswift/youbelongwithme.html", "", ""],
["You Do", "../lyrics/taylorswift/youdo.html", "", ""],
["You're Not Sorry", "../lyrics/taylorswift/yourenotsorry.html", "", ""],
["Your Anything", "../lyrics/taylorswift/youranything.html", "", ""],
["Your Face", "../lyrics/taylorswift/yourface.html", "", ""]];

beatles = [
["1822!", "../lyrics/beatles/1822.html", "", ""],
["A Day In The Life", "../lyrics/beatles/adayinthelife.html", "", ""],
["A Hard Day's Night", "../lyrics/beatles/aharddaysnight.html", "", ""],
["A Little Rhyme", "../lyrics/beatles/alittlerhyme.html", "", ""],
["A Shot Of Rhythm And Blues", "../lyrics/beatles/ashotofrhythmandblues.html", "", ""],
["A Taste Of Honey", "../lyrics/beatles/atasteofhoney.html", "", ""],
["Across The Universe", "../lyrics/beatles/acrosstheuniverse.html", "", ""],
["Act Naturally", "../lyrics/beatles/actnaturally.html", "", ""],
["Ain't She Sweet", "../lyrics/beatles/aintshesweet.html", "", ""],
["All I've Got To Do", "../lyrics/beatles/allivegottodo.html", "", ""],
["All My Loving", "../lyrics/beatles/allmyloving.html", "", ""],
["All Things Must Pass", "../lyrics/beatles/allthingsmustpass.html", "", ""],
["All Together Now", "../lyrics/beatles/alltogethernow.html", "", ""],
["All You Need Is Love", "../lyrics/beatles/allyouneedislove.html", "", ""],
["And I Love Her", "../lyrics/beatles/andiloveher.html", "", ""],
["And Your Bird Can Sing", "../lyrics/beatles/andyourbirdcansing.html", "", ""],
["Anna (Go To Him)", "../lyrics/beatles/annagotohim.html", "", ""],
["Another Girl", "../lyrics/beatles/anothergirl.html", "", ""],
["Any Time At All", "../lyrics/beatles/anytimeatall.html", "", ""],
["Ask Me Why", "../lyrics/beatles/askmewhy.html", "", ""],
["Baby It's You", "../lyrics/beatles/babyitsyou.html", "", ""],
["Baby's In Black", "../lyrics/beatles/babysinblack.html", "", ""],
["Baby, You're A Rich Man", "../lyrics/beatles/babyyourearichman.html", "", ""],
["Back In The U.S.S.R.", "../lyrics/beatles/backintheussr.html", "", ""],
["Bad Boy", "../lyrics/beatles/badboy.html", "", ""],
["Beatle Greetings", "../lyrics/beatles/beatlegreetings.html", "", ""],
["Because", "../lyrics/beatles/because.html", "", ""],
["Being For The Benefit Of Mr. Kite!", "../lyrics/beatles/beingforthebenefitofmrkite.html", "", ""],
["Besame Mucho", "../lyrics/beatles/besamemucho.html", "", ""],
["Birthday", "../lyrics/beatles/birthday.html", "", ""],
["Blackbird", "../lyrics/beatles/blackbird.html", "", ""],
["Blue Jay Way", "../lyrics/beatles/bluejayway.html", "", ""],
["Boys", "../lyrics/beatles/boys.html", "", ""],
["Can't Buy Me Love", "../lyrics/beatles/cantbuymelove.html", "", ""],
["Carol", "../lyrics/beatles/carol.html", "", ""],
["Carry That Weight", "../lyrics/beatles/carrythatweight.html", "", ""],
["Chains", "../lyrics/beatles/chains.html", "", ""],
["Clarabella", "../lyrics/beatles/clarabella.html", "", ""],
["Come And Get It", "../lyrics/beatles/comeandgetit.html", "", ""],
["Come Together", "../lyrics/beatles/cometogether.html", "", ""],
["Crinsk Dee Night", "../lyrics/beatles/crinskdeenight.html", "", ""],
["Cry Baby Cry", "../lyrics/beatles/crybabycry.html", "", ""],
["Crying, Waiting, Hoping", "../lyrics/beatles/cryingwaitinghoping.html", "", ""],
["Day Tripper", "../lyrics/beatles/daytripper.html", "", ""],
["Dear Prudence", "../lyrics/beatles/dearprudence.html", "", ""],
["Dear Wack!", "../lyrics/beatles/dearwack.html", "", ""],
["Devil In Her Heart", "../lyrics/beatles/devilinherheart.html", "", ""],
["Dig A Pony", "../lyrics/beatles/digapony.html", "", ""],
["Dig It", "../lyrics/beatles/digit.html", "", ""],
["Dizzy Miss Lizzy", "../lyrics/beatles/dizzymisslizzy.html", "", ""],
["Do You Want To Know A Secret", "../lyrics/beatles/doyouwanttoknowasecret.html", "", ""],
["Doctor Robert", "../lyrics/beatles/doctorrobert.html", "", ""],
["Don't Bother Me", "../lyrics/beatles/dontbotherme.html", "", ""],
["Don't Ever Change", "../lyrics/beatles/donteverchange.html", "", ""],
["Don't Let Me Down", "../lyrics/beatles/dontletmedown.html", "", ""],
["Don't Pass Me By", "../lyrics/beatles/dontpassmeby.html", "", ""],
["Drive My Car", "../lyrics/beatles/drivemycar.html", "", ""],
["Eight Days A Week", "../lyrics/beatles/eightdaysaweek.html", "", ""],
["Eleanor Rigby", "../lyrics/beatles/eleanorrigby.html", "", ""],
["Every Little Thing", "../lyrics/beatles/everylittlething.html", "", ""],
["Everybody's Got Something To Hide Except Me And My Monkey", "../lyrics/beatles/everybodysgotsomethingtohideexceptmeandmymonkey.html", "", ""],
["Everybody's Trying To Be My Baby", "../lyrics/beatles/everybodystryingtobemybaby.html", "", ""],
["Fixing A Hole", "../lyrics/beatles/fixingahole.html", "", ""],
["Flying", "../lyrics/beatles/flying.html", "", ""],
["For No One", "../lyrics/beatles/fornoone.html", "", ""],
["For You Blue", "../lyrics/beatles/foryoublue.html", "", ""],
["Free As A Bird", "../lyrics/beatles/freeasabird.html", "", ""],
["From Fluff To You", "../lyrics/beatles/fromflufftoyou.html", "", ""],
["From Me To You", "../lyrics/beatles/frommetoyou.html", "", ""],
["From Us To You", "../lyrics/beatles/fromustoyou.html", "", ""],
["Get Back", "../lyrics/beatles/getback.html", "", ""],
["Getting Better", "../lyrics/beatles/gettingbetter.html", "", ""],
["Girl", "../lyrics/beatles/girl.html", "", ""],
["Glad All Over", "../lyrics/beatles/gladallover.html", "", ""],
["Glass Onion", "../lyrics/beatles/glassonion.html", "", ""],
["Golden Slumbers", "../lyrics/beatles/goldenslumbers.html", "", ""],
["Good Day Sunshine", "../lyrics/beatles/gooddaysunshine.html", "", ""],
["Good Morning, Good Morning", "../lyrics/beatles/goodmorninggoodmorning.html", "", ""],
["Good Night", "../lyrics/beatles/goodnight.html", "", ""],
["Got To Get You Into My Life", "../lyrics/beatles/gottogetyouintomylife.html", "", ""],
["Hallelujah, I Love Her So", "../lyrics/beatles/hallelujahiloveherso.html", "", ""],
["Happiness Is A Warm Gun", "../lyrics/beatles/happinessisawarmgun.html", "", ""],
["Have A Banana!", "../lyrics/beatles/haveabanana.html", "", ""],
["Hello Little Girl", "../lyrics/beatles/hellolittlegirl.html", "", ""],
["Hello, Goodbye", "../lyrics/beatles/hellogoodbye.html", "", ""],
["Help!", "../lyrics/beatles/help.html", "", ""],
["Helter Skelter", "../lyrics/beatles/helterskelter.html", "", ""],
["Her Majesty", "../lyrics/beatles/hermajesty.html", "", ""],
["Here Comes The Sun", "../lyrics/beatles/herecomesthesun.html", "", ""],
["Here, There And Everywhere", "../lyrics/beatles/herethereandeverywhere.html", "", ""],
["Hey Bulldog", "../lyrics/beatles/heybulldog.html", "", ""],
["Hey Jude", "../lyrics/beatles/heyjude.html", "", ""],
["Hold Me Tight", "../lyrics/beatles/holdmetight.html", "", ""],
["Honey Don't", "../lyrics/beatles/honeydont.html", "", ""],
["Honey Pie", "../lyrics/beatles/honeypie.html", "", ""],
["How Do You Do It", "../lyrics/beatles/howdoyoudoit.html", "", ""],
["I Am The Walrus", "../lyrics/beatles/iamthewalrus.html", "", ""],
["I Call Your Name", "../lyrics/beatles/icallyourname.html", "", ""],
["I Don't Want To Spoil The Party", "../lyrics/beatles/idontwanttospoiltheparty.html", "", ""],
["I Feel Fine", "../lyrics/beatles/ifeelfine.html", "", ""],
["I Forgot To Remember To Forget", "../lyrics/beatles/iforgottoremembertoforget.html", "", ""],
["I Got A Woman", "../lyrics/beatles/igotawoman.html", "", ""],
["I Got To Find My Baby", "../lyrics/beatles/igottofindmybaby.html", "", ""],
["I Just Don't Understand", "../lyrics/beatles/ijustdontunderstand.html", "", ""],
["I Me Mine", "../lyrics/beatles/imemine.html", "", ""],
["I Need You", "../lyrics/beatles/ineedyou.html", "", ""],
["I Saw Her Standing There", "../lyrics/beatles/isawherstandingthere.html", "", ""],
["I Should Have Known Better", "../lyrics/beatles/ishouldhaveknownbetter.html", "", ""],
["I Wanna Be Your Man", "../lyrics/beatles/iwannabeyourman.html", "", ""],
["I Want To Hold Your Hand", "../lyrics/beatles/iwanttoholdyourhand.html", "", ""],
["I Want To Tell You", "../lyrics/beatles/iwanttotellyou.html", "", ""],
["I Want You (She's So Heavy)", "../lyrics/beatles/iwantyoushessoheavy.html", "", ""],
["I Will", "../lyrics/beatles/iwill.html", "", ""],
["I'll Be Back", "../lyrics/beatles/illbeback.html", "", ""],
["I'll Be On My Way", "../lyrics/beatles/illbeonmyway.html", "", ""],
["I'll Cry Instead", "../lyrics/beatles/illcryinstead.html", "", ""],
["I'll Follow The Sun", "../lyrics/beatles/illfollowthesun.html", "", ""],
["I'll Get You", "../lyrics/beatles/illgetyou.html", "", ""],
["I'm A Loser", "../lyrics/beatles/imaloser.html", "", ""],
["I'm Down", "../lyrics/beatles/imdown.html", "", ""],
["I'm Gonna Sit Right Down And Cry (Over You)", "../lyrics/beatles/imgonnasitrightdownandcryoveryou.html", "", ""],
["I'm Happy Just To Dance With You", "../lyrics/beatles/imhappyjusttodancewithyou.html", "", ""],
["I'm Looking Through You", "../lyrics/beatles/imlookingthroughyou.html", "", ""],
["I'm Only Sleeping", "../lyrics/beatles/imonlysleeping.html", "", ""],
["I'm So Tired", "../lyrics/beatles/imsotired.html", "", ""],
["I've Got A Feeling", "../lyrics/beatles/ivegotafeeling.html", "", ""],
["I've Just Seen A Face", "../lyrics/beatles/ivejustseenaface.html", "", ""],
["If I Fell", "../lyrics/beatles/ififell.html", "", ""],
["If I Needed Someone", "../lyrics/beatles/ifineededsomeone.html", "", ""],
["If You've Got Trouble", "../lyrics/beatles/ifyouvegottrouble.html", "", ""],
["In My Life", "../lyrics/beatles/inmylife.html", "", ""],
["In Spite Of All The Danger", "../lyrics/beatles/inspiteofallthedanger.html", "", ""],
["It Won't Be Long", "../lyrics/beatles/itwontbelong.html", "", ""],
["It's All Too Much", "../lyrics/beatles/itsalltoomuch.html", "", ""],
["It's Only Love", "../lyrics/beatles/itsonlylove.html", "", ""],
["Johnny B. Goode", "../lyrics/beatles/johnnybgoode.html", "", ""],
["Julia", "../lyrics/beatles/julia.html", "", ""],
["Junk", "../lyrics/beatles/junk.html", "", ""],
["Just A Rumour", "../lyrics/beatles/justarumour.html", "", ""],
["Keep Your Hands Off My Baby", "../lyrics/beatles/keepyourhandsoffmybaby.html", "", ""],
["Komm, Gib Mir Deine Hand", "../lyrics/beatles/kommgibmirdeinehand.html", "", ""],
["Lady Madonna", "../lyrics/beatles/ladymadonna.html", "", ""],
["Leave My Kitten Alone", "../lyrics/beatles/leavemykittenalone.html", "", ""],
["Lend Me Your Comb", "../lyrics/beatles/lendmeyourcomb.html", "", ""],
["Let It Be", "../lyrics/beatles/letitbe.html", "", ""],
["Like Dreamers Do", "../lyrics/beatles/likedreamersdo.html", "", ""],
["Little Child", "../lyrics/beatles/littlechild.html", "", ""],
["Lonesome Tears In My Eyes", "../lyrics/beatles/lonesometearsinmyeyes.html", "", ""],
["Long Tall Sally", "../lyrics/beatles/longtallsally.html", "", ""],
["Long, Long, Long", "../lyrics/beatles/longlonglong.html", "", ""],
["Love Me Do", "../lyrics/beatles/lovemedo.html", "", ""],
["Love These Goon Shows!", "../lyrics/beatles/lovethesegoonshows.html", "", ""],
["Love You To", "../lyrics/beatles/loveyouto.html", "", ""],
["Lovely Rita", "../lyrics/beatles/lovelyrita.html", "", ""],
["Lucille", "../lyrics/beatles/lucille.html", "", ""],
["Lucy In The Sky With Diamonds", "../lyrics/beatles/lucyintheskywithdiamonds.html", "", ""],
["Maggie Mae", "../lyrics/beatles/maggiemae.html", "", ""],
["Magical Mystery Tour", "../lyrics/beatles/magicalmysterytour.html", "", ""],
["Mailman, Bring Me No More Blues", "../lyrics/beatles/mailmanbringmenomoreblues.html", "", ""],
["March Of The Meanies", "../lyrics/beatles/marchofthemeanies.html", "", ""],
["Martha My Dear", "../lyrics/beatles/marthamydear.html", "", ""],
["Matchbox", "../lyrics/beatles/matchbox.html", "", ""],
["Maxwell's Silver Hammer", "../lyrics/beatles/maxwellssilverhammer.html", "", ""],
["Mean Mr. Mustard", "../lyrics/beatles/meanmrmustard.html", "", ""],
["Medley: Kansas City / Hey, Hey, Hey, Hey", "../lyrics/beatles/medleykansascityheyheyheyhey.html", "", ""],
["Medley: Rip It Up / Shake, Rattle And Roll / Blue Suede Shoes", "../lyrics/beatles/medleyripitupshakerattleandrollbluesuedeshoes.html", "", ""],
["Medley: Sea Of Time &amp; Sea Of Holes", "../lyrics/beatles/medleyseaoftimeseaofholes.html", "", ""],
["Memphis, Tennessee", "../lyrics/beatles/memphistennessee.html", "", ""],
["Michelle", "../lyrics/beatles/michelle.html", "", ""],
["Misery", "../lyrics/beatles/misery.html", "", ""],
["Money (That's What I Want)", "../lyrics/beatles/moneythatswhatiwant.html", "", ""],
["Moonlight Bay", "../lyrics/beatles/moonlightbay.html", "", ""],
["Mother Nature's Son", "../lyrics/beatles/mothernaturesson.html", "", ""],
["Mr. Moonlight", "../lyrics/beatles/mrmoonlight.html", "", ""],
["My Bonnie", "../lyrics/beatles/mybonnie.html", "", ""],
["No Reply", "../lyrics/beatles/noreply.html", "", ""],
["Norwegian Wood (This Bird Has Flown)", "../lyrics/beatles/norwegianwoodthisbirdhasflown.html", "", ""],
["Not A Second Time", "../lyrics/beatles/notasecondtime.html", "", ""],
["Not Guilty", "../lyrics/beatles/notguilty.html", "", ""],
["Nothin' Shakin'", "../lyrics/beatles/nothinshakin.html", "", ""],
["Nowhere Man", "../lyrics/beatles/nowhereman.html", "", ""],
["Ob-La-Di, Ob-La-Da", "../lyrics/beatles/obladioblada.html", "", ""],
["Octopus's Garden", "../lyrics/beatles/octopussgarden.html", "", ""],
["Oh! Darling", "../lyrics/beatles/ohdarling.html", "", ""],
["Old Brown Shoe", "../lyrics/beatles/oldbrownshoe.html", "", ""],
["One After 909", "../lyrics/beatles/oneafter909.html", "", ""],
["Only A Northern Song", "../lyrics/beatles/onlyanorthernsong.html", "", ""],
["Ooh! My Arms", "../lyrics/beatles/oohmyarms.html", "", ""],
["Ooh! My Soul", "../lyrics/beatles/oohmysoul.html", "", ""],
["P.S. I Love You", "../lyrics/beatles/psiloveyou.html", "", ""],
["Paperback Writer", "../lyrics/beatles/paperbackwriter.html", "", ""],
["Penny Lane", "../lyrics/beatles/pennylane.html", "", ""],
["Pepperland", "../lyrics/beatles/pepperland.html", "", ""],
["Pepperland Laid Waste", "../lyrics/beatles/pepperlandlaidwaste.html", "", ""],
["Piggies", "../lyrics/beatles/piggies.html", "", ""],
["Please Mister Postman", "../lyrics/beatles/pleasemisterpostman.html", "", ""],
["Please Please Me", "../lyrics/beatles/pleasepleaseme.html", "", ""],
["Polythene Pam", "../lyrics/beatles/polythenepam.html", "", ""],
["Rain", "../lyrics/beatles/rain.html", "", ""],
["Real Love", "../lyrics/beatles/reallove.html", "", ""],
["Revolution", "../lyrics/beatles/revolution.html", "", ""],
["Revolution 1", "../lyrics/beatles/revolution1.html", "", ""],
["Revolution 9", "../lyrics/beatles/revolution9.html", "", ""],
["Riding On A Bus", "../lyrics/beatles/ridingonabus.html", "", ""],
["Rock And Roll Music", "../lyrics/beatles/rockandrollmusic.html", "", ""],
["Rocky Raccoon", "../lyrics/beatles/rockyraccoon.html", "", ""],
["Roll Over Beethoven", "../lyrics/beatles/rolloverbeethoven.html", "", ""],
["Run For Your Life", "../lyrics/beatles/runforyourlife.html", "", ""],
["Savoy Truffle", "../lyrics/beatles/savoytruffle.html", "", ""],
["Sea Of Monsters", "../lyrics/beatles/seaofmonsters.html", "", ""],
["Searchin'", "../lyrics/beatles/searchin.html", "", ""],
["Set Fire To That Lot!", "../lyrics/beatles/setfiretothatlot.html", "", ""],
["Sexy Sadie", "../lyrics/beatles/sexysadie.html", "", ""],
["Sgt. Pepper's Lonely Hearts Club Band", "../lyrics/beatles/sgtpepperslonelyheartsclubband.html", "", ""],
["Sgt. Pepper's Lonely Hearts Club Band (Reprise)", "../lyrics/beatles/sgtpepperslonelyheartsclubbandreprise.html", "", ""],
["Sha La La La La!", "../lyrics/beatles/shalalalala.html", "", ""],
["She Came In Through The Bathroom Window", "../lyrics/beatles/shecameinthroughthebathroomwindow.html", "", ""],
["She Loves You", "../lyrics/beatles/shelovesyou.html", "", ""],
["She Said, She Said", "../lyrics/beatles/shesaidshesaid.html", "", ""],
["She's A Woman", "../lyrics/beatles/shesawoman.html", "", ""],
["She's Leaving Home", "../lyrics/beatles/shesleavinghome.html", "", ""],
["Shout", "../lyrics/beatles/shout.html", "", ""],
["Sie Liebt Dich", "../lyrics/beatles/sieliebtdich.html", "", ""],
["Slow Down", "../lyrics/beatles/slowdown.html", "", ""],
["So How Come (No One Loves Me)", "../lyrics/beatles/sohowcomenoonelovesme.html", "", ""],
["Soldier Of Love", "../lyrics/beatles/soldieroflove.html", "", ""],
["Some Other Guy", "../lyrics/beatles/someotherguy.html", "", ""],
["Something", "../lyrics/beatles/something.html", "", ""],
["Step Inside Love / Los Paranoias", "../lyrics/beatles/stepinsidelovelosparanoias.html", "", ""],
["Strawberry Fields Forever", "../lyrics/beatles/strawberryfieldsforever.html", "", ""],
["Sun King", "../lyrics/beatles/sunking.html", "", ""],
["Sure To Fall (In Love With You)", "../lyrics/beatles/suretofallinlovewithyou.html", "", ""],
["Sweet Little Sixteen", "../lyrics/beatles/sweetlittlesixteen.html", "", ""],
["Taxman", "../lyrics/beatles/taxman.html", "", ""],
["Teddy Boy", "../lyrics/beatles/teddyboy.html", "", ""],
["Tell Me What You See", "../lyrics/beatles/tellmewhatyousee.html", "", ""],
["Tell Me Why", "../lyrics/beatles/tellmewhy.html", "", ""],
["Thank You Girl", "../lyrics/beatles/thankyougirl.html", "", ""],
["That Means A Lot", "../lyrics/beatles/thatmeansalot.html", "", ""],
["That'll Be The Day", "../lyrics/beatles/thatllbetheday.html", "", ""],
["That's Alright (Mama)", "../lyrics/beatles/thatsalrightmama.html", "", ""],
["The Ballad Of John And Yoko", "../lyrics/beatles/theballadofjohnandyoko.html", "", ""],
["The Continuing Story Of Bungalow Bill", "../lyrics/beatles/thecontinuingstoryofbungalowbill.html", "", ""],
["The End", "../lyrics/beatles/theend.html", "", ""],
["The Fool On The Hill", "../lyrics/beatles/thefoolonthehill.html", "", ""],
["The Hippy Hippy Shake", "../lyrics/beatles/thehippyhippyshake.html", "", ""],
["The Honeymoon Song", "../lyrics/beatles/thehoneymoonsong.html", "", ""],
["The Inner Light", "../lyrics/beatles/theinnerlight.html", "", ""],
["The Long And Winding Road", "../lyrics/beatles/thelongandwindingroad.html", "", ""],
["The Night Before", "../lyrics/beatles/thenightbefore.html", "", ""],
["The Sheik Of Araby", "../lyrics/beatles/thesheikofaraby.html", "", ""],
["The Word", "../lyrics/beatles/theword.html", "", ""],
["There's A Place", "../lyrics/beatles/theresaplace.html", "", ""],
["Things We Said Today", "../lyrics/beatles/thingswesaidtoday.html", "", ""],
["Think For Yourself", "../lyrics/beatles/thinkforyourself.html", "", ""],
["This Boy", "../lyrics/beatles/thisboy.html", "", ""],
["Three Cool Cats", "../lyrics/beatles/threecoolcats.html", "", ""],
["Ticket To Ride", "../lyrics/beatles/tickettoride.html", "", ""],
["Till There Was You", "../lyrics/beatles/tilltherewasyou.html", "", ""],
["To Know Her Is To Love Her", "../lyrics/beatles/toknowheristoloveher.html", "", ""],
["Tomorrow Never Knows", "../lyrics/beatles/tomorrowneverknows.html", "", ""],
["Too Much Monkey Business", "../lyrics/beatles/toomuchmonkeybusiness.html", "", ""],
["Twist And Shout", "../lyrics/beatles/twistandshout.html", "", ""],
["Two Of Us", "../lyrics/beatles/twoofus.html", "", ""],
["Wait", "../lyrics/beatles/wait.html", "", ""],
["We Can Work It Out", "../lyrics/beatles/wecanworkitout.html", "", ""],
["What Goes On", "../lyrics/beatles/whatgoeson.html", "", ""],
["What You're Doing", "../lyrics/beatles/whatyouredoing.html", "", ""],
["What's The New Mary Jane", "../lyrics/beatles/whatsthenewmaryjane.html", "", ""],
["When I Get Home", "../lyrics/beatles/whenigethome.html", "", ""],
["When I'm Sixty Four", "../lyrics/beatles/whenimsixtyfour.html", "", ""],
["While My Guitar Gently Weeps", "../lyrics/beatles/whilemyguitargentlyweeps.html", "", ""],
["Why Don't We Do It In The Road?", "../lyrics/beatles/whydontwedoitintheroad.html", "", ""],
["Wild Honey Pie", "../lyrics/beatles/wildhoneypie.html", "", ""],
["With A Little Help From My Friends", "../lyrics/beatles/withalittlehelpfrommyfriends.html", "", ""],
["Within You Without You", "../lyrics/beatles/withinyouwithoutyou.html", "", ""],
["Words Of Love", "../lyrics/beatles/wordsoflove.html", "", ""],
["Yellow Submarine", "../lyrics/beatles/yellowsubmarine.html", "", ""],
["Yellow Submarine In Pepperland", "../lyrics/beatles/yellowsubmarineinpepperland.html", "", ""],
["Yer Blues", "../lyrics/beatles/yerblues.html", "", ""],
["Yes It Is", "../lyrics/beatles/yesitis.html", "", ""],
["Yesterday", "../lyrics/beatles/yesterday.html", "", ""],
["You Can't Do That", "../lyrics/beatles/youcantdothat.html", "", ""],
["You Know My Name (Look Up The Number)", "../lyrics/beatles/youknowmynamelookupthenumber.html", "", ""],
["You Know What To Do", "../lyrics/beatles/youknowwhattodo.html", "", ""],
["You Like Me Too Much", "../lyrics/beatles/youlikemetoomuch.html", "", ""],
["You Never Give Me Your Money", "../lyrics/beatles/younevergivemeyourmoney.html", "", ""],
["You Really Got A Hold On Me", "../lyrics/beatles/youreallygotaholdonme.html", "", ""],
["You Won't See Me", "../lyrics/beatles/youwontseeme.html", "", ""],
["You'll Be Mine", "../lyrics/beatles/youllbemine.html", "", ""],
["You're Going To Lose That Girl", "../lyrics/beatles/youregoingtolosethatgirl.html", "", ""],
["You've Got To Hide Your Love Away", "../lyrics/beatles/youvegottohideyourloveaway.html", "", ""],
["Young Blood", "../lyrics/beatles/youngblood.html", "", ""],
["Your Mother Should Know", "../lyrics/beatles/yourmothershouldknow.html", "", ""]];

twentyonepilots = [
["7 Acoustic Covers", "../lyrics/twentyonepilots/7acousticcovers.html", "", ""],
["A Car, A Torch, A Death", "../lyrics/twentyonepilots/acaratorchadeath.html", "", ""],
["Addict With A Pen", "../lyrics/twentyonepilots/addictwithapen.html", "", ""],
["Air Catcher", "../lyrics/twentyonepilots/aircatcher.html", "", ""],
["Anathema", "../lyrics/twentyonepilots/anathema.html", "", ""],
["Be Concerned", "../lyrics/twentyonepilots/beconcerned.html", "", ""],
["Before You Start Your Day", "../lyrics/twentyonepilots/beforeyoustartyourday.html", "", ""],
["Can't Help Falling In Love", "../lyrics/twentyonepilots/canthelpfallinginlove.html", "", ""],
["Car Radio", "../lyrics/twentyonepilots/carradio.html", "", ""],
["Clear", "../lyrics/twentyonepilots/clear.html", "", ""],
["Doubt", "../lyrics/twentyonepilots/doubt.html", "", ""],
["Fairly Local", "../lyrics/twentyonepilots/fairlylocal.html", "", ""],
["Fake You Out", "../lyrics/twentyonepilots/fakeyouout.html", "", ""],
["Fall Away", "../lyrics/twentyonepilots/fallaway.html", "", ""],
["Forest", "../lyrics/twentyonepilots/forest.html", "", ""],
["Friend, Please", "../lyrics/twentyonepilots/friendplease.html", "", ""],
["Glowing Eyes", "../lyrics/twentyonepilots/glowingeyes.html", "", ""],
["Goner", "../lyrics/twentyonepilots/goner.html", "", ""],
["Guns For Hands", "../lyrics/twentyonepilots/gunsforhands.html", "", ""],
["Heathens", "../lyrics/twentyonepilots/heathens.html", "", ""],
["Heavy Dirty Soul", "../lyrics/twentyonepilots/heavydirtysoul.html", "", ""],
["Holding On To You", "../lyrics/twentyonepilots/holdingontoyou.html", "", ""],
["Hometown", "../lyrics/twentyonepilots/hometown.html", "", ""],
["House Of Gold", "../lyrics/twentyonepilots/houseofgold.html", "", ""],
["Implicit Demand For Proof", "../lyrics/twentyonepilots/implicitdemandforproof.html", "", ""],
["Isle Of Flightless Birds", "../lyrics/twentyonepilots/isleofflightlessbirds.html", "", ""],
["Jar Of Hearts", "../lyrics/twentyonepilots/jarofhearts.html", "", ""],
["Johnny Boy", "../lyrics/twentyonepilots/johnnyboy.html", "", ""],
["Kitchen Sink", "../lyrics/twentyonepilots/kitchensink.html", "", ""],
["Lane Boy", "../lyrics/twentyonepilots/laneboy.html", "", ""],
["Lovely", "../lyrics/twentyonepilots/lovely.html", "", ""],
["March To The Sea", "../lyrics/twentyonepilots/marchtothesea.html", "", ""],
["Message Man", "../lyrics/twentyonepilots/messageman.html", "", ""],
["Migraine", "../lyrics/twentyonepilots/migraine.html", "", ""],
["Not Today", "../lyrics/twentyonepilots/nottoday.html", "", ""],
["Ode To Sleep", "../lyrics/twentyonepilots/odetosleep.html", "", ""],
["Oh Ms Believer", "../lyrics/twentyonepilots/ohmsbeliever.html", "", ""],
["Polarize", "../lyrics/twentyonepilots/polarize.html", "", ""],
["Ride", "../lyrics/twentyonepilots/ride.html", "", ""],
["Ruby", "../lyrics/twentyonepilots/ruby.html", "", ""],
["Screen", "../lyrics/twentyonepilots/screen.html", "", ""],
["Semi-Automatic", "../lyrics/twentyonepilots/semiautomatic.html", "", ""],
["Slowtown", "../lyrics/twentyonepilots/slowtown.html", "", ""],
["Stressed Out", "../lyrics/twentyonepilots/stressedout.html", "", ""],
["Stressed Out (Tomsize Remix)", "../lyrics/twentyonepilots/stressedouttomsizeremix.html", "", ""],
["Taxi Cab", "../lyrics/twentyonepilots/taxicab.html", "", ""],
["Tear In My Heart", "../lyrics/twentyonepilots/tearinmyheart.html", "", ""],
["The Judge", "../lyrics/twentyonepilots/thejudge.html", "", ""],
["The Pantaloon", "../lyrics/twentyonepilots/thepantaloon.html", "", ""],
["The Run And Go", "../lyrics/twentyonepilots/therunandgo.html", "", ""],
["Time To Say Goodbye", "../lyrics/twentyonepilots/timetosaygoodbye.html", "", ""],
["Trapdoor", "../lyrics/twentyonepilots/trapdoor.html", "", ""],
["Trees", "../lyrics/twentyonepilots/trees.html", "", ""],
["Truce", "../lyrics/twentyonepilots/truce.html", "", ""],
["We Don't Believe What's On T.V.", "../lyrics/twentyonepilots/wedontbelievewhatsontv.html", "", ""]];

mitski = [
["A Burning Hill", "../lyrics/mitski/aburninghill.html", "", ""],
["A Loving Feeling", "../lyrics/mitski/alovingfeeling.html", "", ""],
["Abbey", "../lyrics/mitski/abbey.html", "", ""],
["Bag Of Bones", "../lyrics/mitski/bagofbones.html", "", ""],
["Because Dreaming Costs Money, My Dear", "../lyrics/mitski/becausedreamingcostsmoneymydear.html", "", ""],
["Brand New City", "../lyrics/mitski/brandnewcity.html", "", ""],
["Carry Me Out", "../lyrics/mitski/carrymeout.html", "", ""],
["Circle", "../lyrics/mitski/circle.html", "", ""],
["Class Of 2013", "../lyrics/mitski/classof2013.html", "", ""],
["Crack Baby", "../lyrics/mitski/crackbaby.html", "", ""],
["Dan The Dancer", "../lyrics/mitski/danthedancer.html", "", ""],
["Door", "../lyrics/mitski/door.html", "", ""],
["Drunk Walk Home", "../lyrics/mitski/drunkwalkhome.html", "", ""],
["Eric", "../lyrics/mitski/eric.html", "", ""],
["Fireworks", "../lyrics/mitski/fireworks.html", "", ""],
["First Love / Late Spring", "../lyrics/mitski/firstlovelatespring.html", "", ""],
["Francis Forever", "../lyrics/mitski/francisforever.html", "", ""],
["Goodbye, My Danish Sweetheart", "../lyrics/mitski/goodbyemydanishsweetheart.html", "", ""],
["Happy", "../lyrics/mitski/happy.html", "", ""],
["Humpty", "../lyrics/mitski/humpty.html", "", ""],
["I Bet On Losing Dogs", "../lyrics/mitski/ibetonlosingdogs.html", "", ""],
["I Don't Smoke", "../lyrics/mitski/idontsmoke.html", "", ""],
["I Want You", "../lyrics/mitski/iwantyou.html", "", ""],
["I Will", "../lyrics/mitski/iwill.html", "", ""],
["Jobless Monday", "../lyrics/mitski/joblessmonday.html", "", ""],
["Last Words Of A Shooting Star", "../lyrics/mitski/lastwordsofashootingstar.html", "", ""],
["Liquid Smooth", "../lyrics/mitski/liquidsmooth.html", "", ""],
["My Body's Made Of Crushed Little Stars", "../lyrics/mitski/mybodysmadeofcrushedlittlestars.html", "", ""],
["Once More To See You", "../lyrics/mitski/oncemoretoseeyou.html", "", ""],
["Pearl Diver", "../lyrics/mitski/pearldiver.html", "", ""],
["Real Men", "../lyrics/mitski/realmen.html", "", ""],
["Shame", "../lyrics/mitski/shame.html", "", ""],
["Square", "../lyrics/mitski/square.html", "", ""],
["Strawberry Blond", "../lyrics/mitski/strawberryblond.html", "", ""],
["Texas Reznikoff", "../lyrics/mitski/texasreznikoff.html", "", ""],
["Thursday Girl", "../lyrics/mitski/thursdaygirl.html", "", ""],
["Townie", "../lyrics/mitski/townie.html", "", ""],
["Wife", "../lyrics/mitski/wife.html", "", ""],
["Your Best American Girl", "../lyrics/mitski/yourbestamericangirl.html", "", ""]];
